
[build.environment]
  NODE_VERSION = "20"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/"
  to = "https://lichao.xin/talks"
  status = 302
